In [1]:
import torch
import numpy as np

print("PyTorch version:", torch.version)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: <module 'torch.version' from 'C:\\Users\\dell\\anaconda3\\Lib\\site-packages\\torch\\version.py'>
CUDA available: False


In [2]:
# 2
tensor_2 = torch.rand((7,7))
print("2) tensor_2 shape:", tensor_2.shape)
print(tensor_2)

2) tensor_2 shape: torch.Size([7, 7])
tensor([[0.8209, 0.7775, 0.8296, 0.1904, 0.3282, 0.5961, 0.9282],
        [0.1197, 0.7674, 0.5356, 0.2731, 0.2326, 0.2510, 0.5755],
        [0.9359, 0.2378, 0.0140, 0.3984, 0.4122, 0.6707, 0.9103],
        [0.5315, 0.0507, 0.9545, 0.3833, 0.4905, 0.8948, 0.1439],
        [0.8960, 0.7998, 0.0658, 0.1272, 0.6487, 0.1103, 0.5673],
        [0.2815, 0.4231, 0.6257, 0.6969, 0.9848, 0.4975, 0.8291],
        [0.9393, 0.6603, 0.7751, 0.7165, 0.3095, 0.7228, 0.8973]])


In [3]:
# 3
tensor_3_b = torch.rand((1,7))
tensor_3_b_t = tensor_3_b.T
matmul_3 = tensor_2 @ tensor_3_b_t
print("3) Result shape:", matmul_3.shape)
print(matmul_3)

3) Result shape: torch.Size([7, 1])
tensor([[2.8501],
        [1.8688],
        [2.0625],
        [2.3048],
        [2.4377],
        [2.9223],
        [3.2989]])


In [4]:
# 4
torch.manual_seed(0)
tensor_4 = torch.rand((7,7))
tensor_4_b = torch.rand((1,7))
tensor_4_b_t = tensor_4_b.T
matmul_4 = tensor_4 @ tensor_4_b_t
print("4) After manual seed(0):")
print(tensor_4)
print(tensor_4_b)
print(matmul_4)

4) After manual seed(0):
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [5]:
# 5
torch.manual_seed(0)
cpu_rand1 = torch.rand(3)
torch.manual_seed(0)
cpu_rand2 = torch.rand(3)
print("5) Equal after same seed:", torch.equal(cpu_rand1, cpu_rand2))
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)
    cuda_rand1 = torch.cuda.FloatTensor(3).uniform_()
    torch.cuda.manual_seed_all(0)
    cuda_rand2 = torch.cuda.FloatTensor(3).uniform_()
    print("CUDA equal after same seed:", torch.equal(cuda_rand1.cpu(), cuda_rand2.cpu()))
else:
    print("CUDA not available.")


5) Equal after same seed: True
CUDA not available.


In [6]:
# 6
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
A = torch.rand((3,2), device=device)
B = torch.rand((2,3), device=device)
print("6) device:", device)
print("A:", A)
print("B:", B)

6) device: cpu
A: tensor([[0.1320, 0.3074],
        [0.6341, 0.4901],
        [0.8964, 0.4556]])
B: tensor([[0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


In [7]:
# 7
matmul_7 = A @ B
print("7) matmul result:", matmul_7)

7) matmul result: tensor([[0.0903, 0.0980, 0.1434],
        [0.4119, 0.3040, 0.3988],
        [0.5770, 0.3897, 0.4940]])


In [8]:
# 8
print("8) max:", matmul_7.max().item(), "min:", matmul_7.min().item())

8) max: 0.5769999027252197 min: 0.09034714847803116


In [9]:
# 9
flat_argmax = torch.argmax(matmul_7)
flat_argmin = torch.argmin(matmul_7)
rows, cols = matmul_7.shape
argmax_pos = (flat_argmax // cols, flat_argmax % cols)
argmin_pos = (flat_argmin // cols, flat_argmin % cols)
print("9) argmax:", argmax_pos, "argmin:", argmin_pos)

9) argmax: (tensor(2), tensor(0)) argmin: (tensor(0), tensor(0))


In [10]:
# 10
torch.manual_seed(42)
t10 = torch.rand((1,1,1,10))
t10_transposed = t10.permute(0,1,3,2)
t10_squeezed = t10_transposed.squeeze()
print("10) t10 shapes:", t10.shape, "->", t10_transposed.shape, "->", t10_squeezed.shape)
print("t10_squeezed:", t10_squeezed)

10) t10 shapes: torch.Size([1, 1, 1, 10]) -> torch.Size([1, 1, 10, 1]) -> torch.Size([10])
t10_squeezed: tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332])
